name: Auto Deploy to cPanel
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploying via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}  # මෙතන SSH_HOST කියන නම secret එකේ නමට සමාන විය යුතුයි
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/repositories/ceylonterrece.com
            git pull origin main
            cp -R frontend/* /home3/ceylonte/public_html/
